language: python
python:
  - 3.6
services:
  - postgresql
install:
  - pip install -r requirements.txt -r requirements-test.txt
  - pip install coveralls
  - ./setup.py build
script:
  ./test.sh
after_success:
  coveralls
