version: '3'

services:

  master:
    image: garncarz/nogamespy-vietcong
    build: .
    command: ./app.py --master
    volumes:
      - ./volume:/app/volume
    ports:
      - 28900:28900
    links:
      - db

  heartbeat:
    image: garncarz/nogamespy-vietcong
    build: .
    command: ./app.py --heartbeat
    volumes:
      - ./volume:/app/volume
    ports:
      - 27900:27900/udp
    links:
      - db

  celery_worker:
    image: garncarz/nogamespy-vietcong
    build: .
    command: celery worker -A nogamespy -l info
    volumes:
      - ./volume:/app/volume
    links:
      - redis
      - db

  celery_beat:
    image: garncarz/nogamespy-vietcong
    build: .
    command: celery beat -A nogamespy -l info
    volumes:
      - ./volume:/app/volume
    links:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
